In [8]:
import pandas as pd

In [5]:
%store -r Census_2011_with_energy

In [6]:
Census_2011_with_energy

                                                      Total Number of Households  \
Postcodes  Small Area Dwelling Type   Period Built
Co. Dublin 267001001  Apartments*     1919 - 1945*                           0.0
                                      1946 - 1960*                           0.0
                                      1961 - 1970*                           0.0
                                      1971 - 1980*                           0.0
                                      1981 - 1990*                           0.0
...                                                                          ...
Dublin 7   267124010  Terraced House* 1981 - 1990*                           0.0
                                      1991 - 2000*                           0.0
                                      2001 - 2005*                           0.0
                                      2006 or later*                         0.0
                                      before 1919*                           0.0

                                                      Average BER HW Demand [MWh/year]  \
Postcodes  Small Area Dwelling Type   Period Built
Co. Dublin 267001001  Apartments*     1919 - 1945*                         2545.361134
                                      1946 - 1960*                         2708.292672
                                      1961 - 1970*                         2720.363263
                                      1971 - 1980*                         2843.005075
                                      1981 - 1990*                         2577.592310
...                                                                                ...
Dublin 7   267124010  Terraced House* 1981 - 1990*                         2886.644800
                                      1991 - 2000*                         2967.237510
                                      2001 - 2005*                         2793.871721
                                      2006 or later*                       2627.525499
                                      before 1919*                         2841.106659

                                                      Average BER SH Demand [MWh/year]  \
Postcodes  Small Area Dwelling Type   Period Built
Co. Dublin 267001001  Apartments*     1919 - 1945*                         8855.781099
                                      1946 - 1960*                         9099.201527
                                      1961 - 1970*                         7433.698571
                                      1971 - 1980*                         7083.608893
                                      1981 - 1990*                         4378.167261
...                                                                                ...
Dublin 7   267124010  Terraced House* 1981 - 1990*                         4848.662210
                                      1991 - 2000*                         5142.857465
                                      2001 - 2005*                         4873.548906
                                      2006 or later*                       2097.831880
                                      before 1919*                        11709.006731

                                                      Number of Samples  \
Postcodes  Small Area Dwelling Type   Period Built
Co. Dublin 267001001  Apartments*     1919 - 1945*                121.0
                                      1946 - 1960*                202.0
                                      1961 - 1970*                172.0
                                      1971 - 1980*                497.0
                                      1981 - 1990*                707.0
...                                                                 ...
Dublin 7   267124010  Terraced House* 1981 - 1990*                312.0
                                      1991 - 2000*                198.0
                                      2001 - 2005*                 35.0
                                      2006 or later*               29.0
                                      before 1919*               1322.0

                                                      Postcode-specific data?  \
Postcodes  Small Area Dwelling Type   Period Built
Co. Dublin 267001001  Apartments*     1919 - 1945*                       True
                                      1946 - 1960*                       True
                                      1961 - 1970*                       True
                                      1971 - 1980*                       True
                                      1981 - 1990*                       True
...                                                                       ...
Dublin 7   267124010  Terraced House* 1981 - 1990*                       True
                                      1991 - 2000*                       True
                                      2001 - 2005*                      False
                                      2006 or later*                    False
                                      before 1919*                       True

                                                      Total BER HW Demand [MWh/year]  \
Postcodes  Small Area Dwelling Type   Period Built
Co. Dublin 267001001  Apartments*     1919 - 1945*                               0.0
                                      1946 - 1960*                               0.0
                                      1961 - 1970*                               0.0
                                      1971 - 1980*                               0.0
                                      1981 - 1990*                               0.0
...                                                                              ...
Dublin 7   267124010  Terraced House* 1981 - 1990*                               0.0
                                      1991 - 2000*                               0.0
                                      2001 - 2005*                               0.0
                                      2006 or later*                             0.0
                                      before 1919*                               0.0

                                                      Total BER SH Demand [MWh/year]
Postcodes  Small Area Dwelling Type   Period Built
Co. Dublin 267001001  Apartments*     1919 - 1945*                               0.0
                                      1946 - 1960*                               0.0
                                      1961 - 1970*                               0.0
                                      1971 - 1980*                               0.0
                                      1981 - 1990*                               0.0
...                                                                              ...
Dublin 7   267124010  Terraced House* 1981 - 1990*                               0.0
                                      1991 - 2000*                               0.0
                                      2001 - 2005*                               0.0
                                      2006 or later*                             0.0
                                      before 1919*                               0.0

[173016 rows x 7 columns]

In [9]:
##  Aggregate data at SA level

Dublin_SA_energy = pd.DataFrame()

Dublin_SA_energy = Census_2011_with_energy.reset_index().pivot_table(
    index=["Postcodes", "Small Area"],
    aggfunc={
        "Total BER HW Demand [MWh/year]": "sum",
        "Total BER SH Demand [MWh/year]": "sum",
        "Postcode-specific data?": "sum",
        "Total Number of Households": "sum",
    },
)
Dublin_SA_energy.rename(
    columns={
        "Total BER HW Demand [MWh/year]": "HW",
        "Total BER SH Demand [MWh/year]": "SH",
        "Postcode-specific data?": "Postcode_specific",
        "Total Number of Households": "TotalHH",
    },
    inplace=True,
)
Dublin_SA_energy.reset_index(inplace=True)
Dublin_SA_energy.drop(columns="Postcodes", inplace=True)

Dublin_SA_energy.head()

  Small Area  Postcode_specific             HW             SH  TotalHH
0  267001001               36.0  181679.873534  254629.945931     65.0
1  267001002               36.0  247618.747340  354231.833969     89.0
2  267001003               36.0  270560.678689  375871.756815     97.0
3  267001004               36.0  291820.513199  419351.725033    104.0
4  267001005               36.0  309348.038793  403035.017223    112.0

In [10]:
%store Census_2011_with_energy
%store Dublin_SA_energy

Stored 'Census_2011_with_energy' (DataFrame)
Stored 'Dublin_SA_energy' (DataFrame)