In [1]:
import pandas as pd
import numpy as np

In [2]:
%store -r BER_Dublin_specific

BER_Dublin_specific.head()

,Postcodes,DwellingTypeDescr,Year_of_Construction,DeliveredEnergyMainWater,MainWaterHeatingFuel,WHMainSystemEff,WHEffAdjFactor,DeliveredEnergySupplementaryWater,SupplWHFuel,DeliveredEnergyMainSpace,...,SupplSHFuel,ElecImmersionInSummer,SolarHeatFraction,HSSupplHeatFraction,CHPSystemType,CHPUnitHeatFraction,gsdHSSupplHeatFraction,TotalFloorArea,gsdHSSupplHeatFraction_edited,HSSupplSystemEff_edited
2,Co. Dublin,Mid-terrace house,2003,5744.089,Mains Gas,90.3,0.95,0.000,None,10826.731,...,8.0,NO,0.0,0.1,NaN,0.0,NaN,131.48,NaN,0.30
6,Dublin 14,Semi-detached house,1962,4287.963,Mains Gas,72.0,0.95,1041.995,Electricity,20046.920,...,2.0,YES,0.0,0.1,NaN,0.0,NaN,95.34,NaN,0.72
15,Dublin 11,End of terrace house,1972,4087.056,Mains Gas,65.0,0.95,840.445,Electricity,14756.551,...,2.0,YES,0.0,0.1,NaN,0.0,NaN,87.76,NaN,0.63
18,Dublin 12,Mid-terrace house,1939,5879.203,Mains Gas,65.0,0.95,0.000,None,11019.516,...,2.0,NO,0.0,0.1,NaN,0.0,NaN,59.31,NaN,0.40
22,Dublin 18,Top-floor apartment,2004,3348.863,Mains Gas,78.3,0.95,824.336,Electricity,8743.726,...,1.0,YES,0.0,0.0,NaN,0.0,NaN,74.56,NaN,0.00

In [3]:
def convert_year_construction_to_CSO_period_built(year_built):

    if year_built == None:
        return "Not stated*"
    elif year_built < 1920:
        return "before 1919*"
    elif year_built < 1946:
        return "1919 - 1945*"
    elif year_built < 1961:
        return "1946 - 1960*"
    elif year_built < 1971:
        return "1961 - 1970*"
    elif year_built < 1981:
        return "1971 - 1980*"
    elif year_built < 1991:
        return "1981 - 1990*"
    elif year_built < 2001:
        return "1991 - 2000*"
    elif year_built < 2006:
        return "2001 - 2005*"
    elif year_built < 2020:
        return "2006 or later*"
    else:
        print(year_built)
        return None


convert_year_construction_to_CSO_period_built = np.vectorize(
    convert_year_construction_to_CSO_period_built
)

BER_Dublin_specific[
    "Period Built"
] = convert_year_construction_to_CSO_period_built(
    BER_Dublin_specific["Year_of_Construction"].values
)

BER_Dublin_specific["Period Built"] = BER_Dublin_specific[
    "Period Built"
].astype("category")

BER_Dublin_specific[["Postcodes","Period Built"]].head()

     Postcodes  Period Built
2   Co. Dublin  2001 - 2005*
6    Dublin 14  1961 - 1970*
15   Dublin 11  1971 - 1980*
18   Dublin 12  1919 - 1945*
22   Dublin 18  2001 - 2005*

In [4]:
%store BER_Dublin_specific

Stored 'BER_Dublin_specific' (DataFrame)