Stack:
https://stackoverflow.com/questions/36843122/how-to-find-the-closest-match-based-on-2-keys-from-one-dataframe-to-another

GIS stack:
https://gis.stackexchange.com/questions/222315/geopandas-find-nearest-point-in-other-dataframe

Google search:
https://www.google.com/search?client=firefox-b-d&q=pandas+match+nearby+gps+coordinates

In [21]:
import pandas as pd

Read in data
---

In [24]:
VO = pd.read_pickle(
    "Data/DataFrame_VO_with_GPS.pkl"
)

In [1]:
print("VO data with GPS attached")

VO data with GPS attached

In [25]:
VO

,X ITM,Y ITM,Property Number,Local Authority,Valuation,Category,Uses,Car Park,Level,Floor Use,Area,Nav Per M2,Nav,Address,Latitude,Longitude
0,716629.21,733761.62,837643,DUBLIN CITY COUNCIL,0,CENTRAL VALUATION LIST,"NETWORK (TELECOM), TELEPHONE (EXCHANGE)",0,1,OFFICE(S),220.00,0.0,0.00,12 DENZILLE LANE DUBLIN 2,53.341216,-6.248594
1,716629.21,733761.62,837643,DUBLIN CITY COUNCIL,0,CENTRAL VALUATION LIST,"NETWORK (TELECOM), TELEPHONE (EXCHANGE)",0,-1,CAR SPACES (NO. OF),2.00,0.0,0.00,12 DENZILLE LANE DUBLIN 2,53.341216,-6.248594
2,716658.26,733255.97,791577,DUBLIN CITY COUNCIL,89100,RETAIL (SHOPS),"CONVENIENCE STORE [<200 SQ. M.], OFF-LICENCE",0,2,TOILETS,24.67,100.0,2467.00,47-48 Lower Baggot Street Dublin 2,53.336668,-6.248344
3,716658.26,733255.97,791577,DUBLIN CITY COUNCIL,89100,RETAIL (SHOPS),"CONVENIENCE STORE [<200 SQ. M.], OFF-LICENCE",0,2,STORE,64.52,100.0,6452.00,47-48 Lower Baggot Street Dublin 2,53.336668,-6.248344
4,716658.26,733255.97,791577,DUBLIN CITY COUNCIL,89100,RETAIL (SHOPS),"CONVENIENCE STORE [<200 SQ. M.], OFF-LICENCE",0,1,STORE,33.06,120.0,3967.20,47-48 Lower Baggot Street Dublin 2,53.336668,-6.248344
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18536,714459.65,727916.47,495305,SOUTH DUBLIN COUNTY COUNCIL,28300,RETAIL (SHOPS),"SHOP, -",0,1,STORE,18.50,170.0,3145.00,1 St Endas Drive Rathfarnham Dublin 14,53.289183,-6.283267
18537,714459.65,727916.47,495305,SOUTH DUBLIN COUNTY COUNCIL,28300,RETAIL (SHOPS),"SHOP, -",0,1,OFFICE(S),14.76,170.0,2509.20,1 St Endas Drive Rathfarnham Dublin 14,53.289183,-6.283267
18538,714459.65,727916.47,495305,SOUTH DUBLIN COUNTY COUNCIL,28300,RETAIL (SHOPS),"SHOP, -",0,0,OFF LICENCE,2955.00,1.0,2955.00,1 St Endas Drive Rathfarnham Dublin 14,53.289183,-6.283267
18539,710810.67,729798.36,5002614,SOUTH DUBLIN COUNTY COUNCIL,11470,RETAIL (SHOPS),"SHOP, -",0,0,RETAIL ZONE A,25.20,330.0,8316.00,St James Road Walkinstown Dublin 12,53.306864,-6.337314
18540,710810.67,729798.36,5002614,SOUTH DUBLIN COUNTY COUNCIL,11470,RETAIL (SHOPS),"SHOP, -",0,0,RETAIL ZONE B,19.17,165.0,3163.05,St James Road Walkinstown Dublin 12,53.306864,-6.337314

In [7]:
EPA = pd.read_excel(r"Data/EPA Reports with Address.xlsx")

In [2]:
print("EPA data with GPS attached")

EPA data with GPS attached

In [9]:
EPA

,Title,Date,Licence Number,"National Grid Reference (6E, 6N)",Address,Latitude,Longitude,URL,URL_by_address
0,Advanced Environmental Solutions (Ireland) Lim...,AER Reporting Year 2018,W0222-01,NaN,"Coldwinters, Blakescross, Lusk, Dublin",53.526326,-6.165884,"https://maps.google.com/?q=53.52632639999999,-...",https://www.google.com/maps/place/Coldwinters ...
1,Alexion Pharma International Trading Ltd,NaN,P1030-1,"E307777, N241121","College Business & Technology Park, Blanchards...",53.407065,-6.373773,"https://maps.google.com/?q=53.4070653,-6.3737734",https://www.google.com/maps/place/College Busi...
2,Amcor Flexibles,NaN,P0119-02,NaN,Jamestown Road Finglas Fublin,53.397429,-6.292017,"https://maps.google.com/?q=53.39742949999999,-...",https://www.google.com/maps/place/Jamestown Ro...
3,Amgen Technology Ireland,AER Reporting Year 2018,P0019-02,"-6.14958, 53.2718","Pottery Road, Dun Laoghaire, Dublin",53.273591,-6.153508,"https://maps.google.com/?q=53.27359089999999,-...",https://www.google.com/maps/place/Pottery Road...
4,Arch Chemicals B.V,NaN,P0060-01,NaN,"Watery Lane, Swords, Co.Dublin",53.462965,-6.222191,"https://maps.google.com/?q=53.46296479999999,-...",https://www.google.com/maps/place/Watery Lane ...
...,...,...,...,...,...,...,...,...,...
61,SunChemical Inks Ltd.,AER Reporting Year 2018,NaN,NaN,"SunChemical Inks Ltd. Glenside House, Mill Lan...",53.358915,-6.361714,"https://maps.google.com/?q=53.3589154,-6.3617144",https://www.google.com/maps/place/SunChemical ...
62,Synergen Power Ltd,AER Reporting Year 2018,P0486-02,-6.20404 53.3397,"Pigeon House Road, Dublin 4",53.343632,-6.222005,"https://maps.google.com/?q=53.3436318,-6.2220048",https://www.google.com/maps/place/Pigeon House...
63,Takeda Ireland Limited (Grange Castle,AER Reporting Year 2018,P0693-02,"103819 E, 390659 N",Grange Castle Business Park Nangor Road Dublin 22,53.328573,-6.439542,"https://maps.google.com/?q=53.3285727,-6.43954...",https://www.google.com/maps/place/Grange Castl...
64,The Hammond Lane Metal Company,AER Reporting Year 2018,P1002- 01,NaN,"The Hammond Lane Metal Co. Ltd\nRingsend , Dub...",53.342176,-6.202346,"https://maps.google.com/?q=53.34217599999999,-...",https://www.google.com/maps/place/The Hammond ...
65,Viridian Power / Huntstown Power Station Phase 2,AER Reporting Year 2018,P0777-02,"-6.32607, 53.4116","Huntstown Power station , Finglas, Dublin 11",53.410968,-6.325752,"https://maps.google.com/?q=53.41096779999999,-...",https://www.google.com/maps/place/Huntstown Po...

Use the haversine function to match buildings based on nearest GPS location
---
<span style="color:red"> __INCOMPLETE__ </span>

In [26]:
def haversine_np(lon1, lat1, lon2, lat2):
    """ Docstring:
        Calculate the great circle distance between two points
        on the earth (specified in decimal degrees)

        All args must be of equal length.    

        Source: https://stackoverflow.com/questions/29545704/fast-haversine-approximation-python-pandas/29546836#29546836

        """
    
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2

    c = 2 * np.arcsin(np.sqrt(a))
    km = 6367 * c
    
    return km

In [27]:
haversine_np(VO['Longitude'],VO['Latitude'],EPA['Longitude'],EPA['Latitude'])

0          21.286714
0        1040.685696
0           4.876921
0          27.610742
1          11.064205
            ...
49788            NaN
49789            NaN
49790            NaN
49791            NaN
49792            NaN
Length: 98657, dtype: float64

In [15]:
from math import cos, asin, sqrt

def distance(lat1, lon1, lat2, lon2):
    p = 0.017453292519943295
    a = 0.5 - cos((lat2-lat1)*p)/2 + cos(lat1*p)*cos(lat2*p) * (1-cos((lon2-lon1)*p)) / 2
    return 12742 * asin(sqrt(a))

def closest(data, v):
    return min(data, key=lambda p: distance(v['lat'],v['lon'],p['lat'],p['lon']))

tempDataList = [{'lat': 39.7612992, 'lon': -86.1519681}, 
                {'lat': 39.762241,  'lon': -86.158436 }, 
                {'lat': 39.7622292, 'lon': -86.1578917}]

v = {'lat': 39.7622290, 'lon': -86.1519750}
print(closest(tempDataList, v))

# https://stackoverflow.com/questions/41336756/find-the-closest-latitude-and-longitude

{'lat': 39.7612992, 'lon': -86.1519681}

In [29]:
from math import cos, asin, sqrt


def distance(lat1, lon1, lat2, lon2):
    p = 0.017453292519943295
    a = (
        0.5
        - cos((lat2 - lat1) * p) / 2
        + cos(lat1 * p) * cos(lat2 * p) * (1 - cos((lon2 - lon1) * p)) / 2
    )
    return 12742 * asin(sqrt(a))


# def closest(lat1, lon1, lat2, lon2):
#     return min(data, key=lambda p: distance(lat,lon,p['Latitude'],p['Longitude']))

distance_vectorised = np.vectorize(distance)

def match_nearest_distance (row):
    np.min(
        distance_vectorised(
            row["Latitude"], row["Longitude"], EPA["Latitude"], EPA["Longitude"]
    )

VO.apply(match_nearest_distance),axis='columns'

0        1.785516
1        1.785516
2        1.912494
3        1.912494
4        1.912494
           ...
18536    4.881045
18537    4.881045
18538    4.881045
18539    0.999750
18540    0.999750
Length: 98657, dtype: float64